<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Tailbook.Modules.Notifications.Application</AssemblyName>
    <RootNamespace>Tailbook.Modules.Notifications.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Tailbook.Modules.Notifications.Domain.csproj" />
    <ProjectReference Include="..\..\..\Tailbook.SharedKernel\Tailbook.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\Tailbook.BuildingBlocks\Tailbook.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\..\Modules\Notifications\Api.Contracts\Tailbook.Modules.Notifications.Api.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ErrorOr" Version="2.0.1" />
    <PackageReference Include="FastEndpoints" Version="8.1.0" />
  </ItemGroup>
</Project>
