<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Tailbook.Modules.Pets.Api</AssemblyName>
    <RootNamespace>Tailbook.Modules.Pets.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Api.Contracts\Tailbook.Modules.Pets.Api.Contracts.csproj" />
    <ProjectReference Include="..\Application\Tailbook.Modules.Pets.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\Tailbook.Modules.Pets.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Tailbook.BuildingBlocks\Tailbook.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\Identity\Api.Contracts\Tailbook.Modules.Identity.Api.Contracts.csproj" />
    <ProjectReference Include="..\..\Customer\Api.Contracts\Tailbook.Modules.Customer.Api.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tailbook.Modules.Pets.Tests" />
  </ItemGroup>
</Project>