global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector:8889"]
        labels:
          service: tailbook-api

  - job_name: "tailbook-api"
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:5001"]
        labels:
          service: tailbook-api
