FROM caddy:2-alpine

COPY ops/caddy/Caddyfile /etc/caddy/Caddyfile

RUN caddy validate --config /etc/caddy/Caddyfile \
    --adapter caddyfile

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD wget -qO- http://localhost:2019/config/ >/dev/null || exit 1

EXPOSE 80 443
