global using Tailbook.Modules.Catalog.Application.Catalog.Models;
global using Tailbook.Modules.Catalog.Application.Catalog.Commands;
global using Tailbook.Modules.Catalog.Application.Catalog.Queries;
global using Tailbook.Modules.Catalog.Application.Catalog.Imports;
global using Tailbook.Modules.Catalog.Domain;
global using Tailbook.Modules.Catalog.Domain.Aggregates;
global using Tailbook.Modules.Catalog.Api.Contracts.Abstractions;
global using Tailbook.Modules.Pets.Api.Contracts.Abstractions;
global using Tailbook.Modules.Catalog.Domain.Entities;
