<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Tailbook.Modules.Booking.IntegrationEvents</AssemblyName>
    <RootNamespace>Tailbook.Modules.Booking.IntegrationEvents</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Tailbook.BuildingBlocks\Tailbook.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\..\Tailbook.SharedKernel\Tailbook.SharedKernel.csproj" />
  </ItemGroup>
</Project>
