<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Tailbook.Modules.Booking.Domain</AssemblyName>
    <RootNamespace>Tailbook.Modules.Booking.Domain</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Tailbook.SharedKernel\Tailbook.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\Tailbook.BuildingBlocks\Tailbook.BuildingBlocks.csproj" />
    <ProjectReference Include="..\IntegrationEvents\Tailbook.Modules.Booking.IntegrationEvents.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ErrorOr" Version="2.0.1" />
  </ItemGroup>
</Project>
